version: "3"

services:
    web:
        image: kevinkao/nginx-golang
        volumes:
            - ./src:/go/src
            - ./database:/go/database
            - ./Makefile:/go/Makefile
            - ./config:/go/config
        ports:
            - "8383:80"
        links:
            - db
        environment:
            - TZ=Asia/Taipei

    db:
        image: mariadb:10.2
        volumes:
            - ./docker/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=develop
            - MYSQL_ROOT_PASSWORD=123456

